# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r


matrix:
  include:
      - language: R
  sudo: false
  cache: packages

  addons:
    apt:
      sources:
        - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
      packages:
        - libudunits2-dev
        - libgdal-dev
        - libgeos-dev
        - libproj-dev

      after_success:
          - Rscript -e 'covr::codecov()'

    - language: java
      jdk: oraclejdk8
